/** @jsxImportSource theme-ui */

import type { NextPage } from "next";
import Head from "next/head";
import ArticleCard, { ArticleVariant } from "../components/Cards/ArticleCard";
import MultiInfoCard from "../components/Cards/MultiInfoCard";
import Carousel, { CarouselItem, CarouselProps } from "../components/Carousel";
import ArticleGrid from "../components/Grids/ArticleGrid";
import ContentGrid from "../components/Grids/ContentGrid";
import SectionHeading from "../components/SectionHeading";
import SectionWrapper from "../components/Wrappers/SectionWrapper";
import { colors } from "../styles/theme";
import { ColorTheme, ComponentVariant } from "../types/modifier";
import { Blocks, BlockType } from "../utils/blocks";

const largeMultiInfoComponentText =
  "[Large multi info component]: Trent Alexander-Arnold's goal against AFC Bournemouth was the 800th Liverpool have scored under Jürgen Klopp in all competitions";

const Home: NextPage = () => {
  const link = {
    label: "this is a label",
    href: "https://liverpoolfc.com",
    external: false,
  };

  const blocks: Blocks[] = [
    {
      id: "1",
      type: BlockType.NEWSCARD,
      imageIndex: 1,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
    {
      id: "3",
      type: BlockType.NEWSCARD,
      imageIndex: 2,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
    {
      id: "4",
      type: BlockType.NEWSCARD,
      imageIndex: 1,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
    {
      id: "5",
      type: BlockType.NEWSCARD,
      imageIndex: 2,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
    {
      id: "8",
      type: BlockType.MULTIINFOCARD,
      label:
        "This is a label. Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
      variant: ComponentVariant.SMALL,
    },
    {
      id: "6",
      type: BlockType.NEWSCARD,
      imageIndex: 1,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
    {
      id: "7",
      type: BlockType.NEWSCARD,
      imageIndex: 2,
      theme: ColorTheme.DARK,
      variant: ArticleVariant.SMALL,
    },
  ];

  const element: JSX.Element = (
    <ArticleCard
      imageIndex={2}
      variant={ArticleVariant.SMALL}
      styles={{ height: "100%" }}
    />
  );

  const element2: JSX.Element = (
    <MultiInfoCard
      label={`Lorem ipsum lorem ipsum lorem ipsum`}
      variant={ComponentVariant.SMALL}
      styles={{ height: "100%" }}
    />
  );

  const items: CarouselItem[] = [
    {
      content: element,
      slideStyles: {},
    },
    {
      content: element,
      slideStyles: {},
    },
    {
      content: element,
      slideStyles: {},
    },
    {
      content: element,
      slideStyles: {},
    },
    {
      content: element,
      slideStyles: {},
    },
  ];

  return (
    <section>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentGrid blocks={blocks} />
      <ArticleGrid />

      {/* <MultiInfoCard
        label={largeMultiInfoComponentText}
        variant={ComponentVariant.LARGE}
      /> */}
      {/* <SectionHeading title={`title`} theme={ColorTheme.LIGHT} link={link} /> */}

      {/* <Carousel swiperId="1" items={items} /> */}

      <SectionWrapper>
        {items.length > 0 ? (
          <Carousel swiperId="1" items={items} styles={{ gap: [1] }} />
        ) : (
          <>Swiper not found</>
        )}
      </SectionWrapper>
    </section>
  );
};

export default Home;
